main: com.winthier.linkportal.LinkPortalPlugin
name: LinkPortal

version: 0.1
api-version: '1.21'

description: Link parallel worlds via nether portals
author: StarTux
website: http://cavetale.com

depend: [Core]
softdepend: []

commands:

  LinkPortal:
    description: Admin interface
    usage: |-
      /linkportal list - List your link portals
      /linkportal reload - Reload (admins)
      /linkportal server - Make server portal (admins)
    permission: linkportal.linkportal

permissions:
  linkportal.linkportal:
    description: Use the "/linkportal" command
    default: op
  linkportal.create:
    description: Create a LinkPortal portal
    default: op
  linkportal.portal:
    description: Create a custom Nether portal
    default: op
  linkportal.admin:
    description: Do admin stuff
    default: op
  linkportal.use:
    description: Use a link portal.
    default: op